### ISSUE TITLE
Error (missing sheet)

### ISSUE THREAD

**Issue by stringfellow** [kobotoolbox/dkobo#525]
I added a form, then duplicated it, then immediately deleted the duplicate, and now the form does not load.

 Here's the JSON response from the XHR:

```
description: null
id: 8870
name: "3W"
summary: "{"error":"You must have a sheet named (case-sensitive): survey"}"
tags: []
```

**Comment by dorey** [comment]
Thanks for reporting this, @stringfellow . We missed it when you first reported it, but we pushed up a fix to prevent the error from continuing. A solid fix is coming in the next week or so.
