### ISSUE TITLE
Transition html popup

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/dkobo#608]
The text displayed should be: 

`KoBoToolbox will be unavailable due to scheduled downtime for a server upgrade from 11PM GMT on Saturday (7 November), for no longer than two hours. Please ensure you have saved all your work prior to this time. `

It should be displayed in the bottom of KF and KC pages on OCHA (11/5-11/7).

**Comment by tinok** [comment]
```html
<div style="
    position: fixed;
    bottom: 0px;
    z-index: 100;
    background-color: rgba(0,0,0,0.6);
    color: white;
    font-size: 11px;
    width: 100%;">

   <p style="margin: 6px 20px 5px;">KoBoToolbox will be unavailable due to scheduled downtime for a server upgrade from 11PM GMT on Saturday (7 November), for no longer than two hours. Please ensure you have saved all your work prior to this time.</p> 

   </div>
```

**Comment by tinok** [comment]
Will look like this: 

![image](https://cloud.githubusercontent.com/assets/673511/10890124/3a549bcc-8164-11e5-915c-150d221a187a.png)

**Comment by teodorescuserban** [comment]
nice!

**Comment by dorey** [comment]
Ok, the code to pull the value from the `SitewideMessage` model is built. It's done except for the design.

@pmusaraj , when you get to this, open up the admin interface and add a SitewideMessage with the slug `user_notification` and markdown in the `body` field. It will display the message at the bottom of the page. The code is on [this branch](https://github.com/kobotoolbox/dkobo/compare/608-user-notification)
